### ISSUE TITLE
Feature Request For Disabling Dark Mode

### ISSUE THREAD

**Issue by tak2hu** [kishikawakatsumi/WebTranslator#139]
First I’d like to say thanks for making this!

Secondly, I’d like to suggest this to have a lighter color of the logo icon when browsing using dark mode. Or an option to switch just this extension into light mode when I’m using system-wide dark mode but just the icon and not the pop up, thanks!

**Comment by kishikawakatsumi** [comment]
Dark mode support cannot be disabled, as it is required for AppStore review. Toolbar icons are automatically colored by Safari and cannot be controlled from here.

**Comment by tak2hu** [comment]
Oh ok thanks for the reply
