### ISSUE TITLE
icon press to translate the selected words

### ISSUE THREAD

**Issue by ZhaoJunnNie** [kishikawakatsumi/WebTranslator#162]
Thanks for your work, and can you add the feature for this APP on Mac to have an icon to press so that the selected words can be translated just like deepl extension on Edge/Chrome.

**Comment by kishikawakatsumi** [comment]
@ZhaoJunnNie Thanks for the request. Just to confirm, the feature you are talking about is the button shown in this screenshot, correct?

<img width="532" alt="Screenshot 2023-08-21 at 15 15 24" src="https://github.com/kishikawakatsumi/WebTranslator/assets/40610/7f23ab95-448d-48b5-9a8f-c44f42c8af91">

**Comment by ZhaoJunnNie** [comment]
> @ZhaoJunnNie Thanks for the request. Just to confirm, the feature you are talking about is the button shown in this screenshot, correct?
> 
> <img alt="Screenshot 2023-08-21 at 15 15 24" width="532" src="https://user-images.githubusercontent.com/40610/261935129-7f23ab95-448d-48b5-9a8f-c44f42c8af91.png">

Thanks for your reply. 
yes!  That's the right feature I am talking about,  and this really helps me when I use the DeepL extension on Edge

**Comment by kishikawakatsumi** [comment]
@ZhaoJunnNie In the latest version (0.1.27), The setting to enable the "Translate Selection" button is now open to non-touch devices.


<img width="550" alt="Screenshot 2023-10-10 at 0 27 48" src="https://github.com/kishikawakatsumi/WebTranslator/assets/40610/82fc6081-d075-42b1-9e87-76dd8fb77f57">


<img width="726" alt="Screenshot 2023-10-10 at 0 28 12" src="https://github.com/kishikawakatsumi/WebTranslator/assets/40610/227873ba-0f27-4908-8836-1233723a75a4">
