### ISSUE TITLE
Sorry, your session expired. Please log in again.

### ISSUE THREAD

**Issue by beremour** [kishikawakatsumi/WebTranslator#170]
Safari extension gives just that

**Comment by kishikawakatsumi** [comment]
Please login again. Failed to log in? @beremour

**Comment by maxibenner** [comment]
@beremour Do you have a paid subscription for DeepL? The error message doesn't make this clear but it will also appear if you are only on the free plan.

**Comment by kishikawakatsumi** [comment]
Closing due to no response. Feel free to reopen if the issue still exists.
