### ISSUE TITLE
DeepL supports more languages

### ISSUE THREAD

**Issue by SchroedersKater** [kishikawakatsumi/WebTranslator#176]
Could you please add the remaining languages? E.g. Netherlands is still missing, but DeepL supports it.

Thank you very much!

**Comment by kishikawakatsumi** [comment]
Thank you for let me know. Netherlands is supported by Deepl.com but does not appear to be supported yet by extension. I will try it once and add it as a supported language if it is usable.

**Comment by SchroedersKater** [comment]
Thank you for this information!
looking forward to a new version. 
I’ve already used Netherlands several times. Of course not with your app ;-) .

**Comment by kishikawakatsumi** [comment]
@SchroedersKater I can't find the language "Netherlands" on DeepL.com, is it really supported by DeepL? If you mean Dutch, we already support it in this extension.
<img width="697" alt="Screenshot 2023-10-09 at 11 22 44" src="https://github.com/kishikawakatsumi/WebTranslator/assets/40610/eedd4d18-c9ec-4e78-8d38-5722f6d0c2e9">

**Comment by SchroedersKater** [comment]
You are completely right! I apologise for my ignorance. Very sorry. Thank you for your patience with this.

**Comment by kishikawakatsumi** [comment]
Thanks for confirming.
