### ISSUE TITLE
Sorry, your session expired. Please log in again.

### ISSUE THREAD

**Issue by vpravdivy** [kishikawakatsumi/WebTranslator#217]
The error is appearing in the Safari extension for Mac and iOS despite having an active Pro subscription (checked). I have attempted to resolve the issue by reinstalling the extension and running it directly from Xcode but to no avail. This has been a persistent issue for over a week now. Is it possible that changes were made to the API? A similar issue occurred a few months ago, and an update was released at that time.

**Comment by kishikawakatsumi** [comment]
@volodymyr-pravdivy That is the expected behavior of the DeepL account; logging in with a different device or browser will invalidate any other login session for the DeepL account. This is not an issue with this extension, but it also happens when you log in to deepl.com with a browser. For example, if you log in to DeepL in Safari and then log in to Chrome or another device, your Safari DeepL account will be logged out.

**Comment by kishikawakatsumi** [comment]
@vpravdivy I understand the problem. However, I have not experienced such a problem on my end, so it seems that the API of DeepL has not changed. I am also unable to reproduce the problem so I cannot investigate the issue. Can you try creating an account with a different email address? If the problem still occurs with the new, different account, please provide that account information so we can investigate.

**Comment by reilly68** [comment]
I've had the same problem for several weeks [see this](https://youtu.be/4V-P43k-dVQ?si=pO4GEPR2rEQDjGs-) Is it possible that the api was changed only for some regions?

**Comment by kishikawakatsumi** [comment]
Excellent. Thanks for doing the investigation. I don't know the cause, but I will try to fix it with this information, and I may ask you to verify it with TestFlight. @vpravdivy

**Comment by twosom** [comment]
same problem here

![image](https://github.com/kishikawakatsumi/WebTranslator/assets/72733442/9c24e49a-6ce2-43ef-bdeb-eea32c8f6999)

**Comment by kishikawakatsumi** [comment]
@vpravdivy Thank you very much. I would love to use your account for investigation. If I can reproduce the problem on my end, I will be able to fix it right away. My email address is kishikawakatsumi@mac.com .

**Comment by kishikawakatsumi** [comment]
Thank you. I was able to reproduce the issue on my side. As a solution, I use different API to retrieve account information. I distribute the fixed version on TestFlight. Can you please confirm that the issue has been resolved?

The bugfixed version is:
0.1.31 (315)


@vpravdivy @twosom @reilly68  

https://testflight.apple.com/join/QmZCoDZb

**Comment by kishikawakatsumi** [comment]
Thanks for quick confirmation. I will check it for a while and if there are no problems on my hand, I will submit it for review as soon as possible.

**Comment by twosom** [comment]
I checked on my iPad and it runs very well.

**Comment by kishikawakatsumi** [comment]
@twosom Thank you.
The version is currently waiting for review. Probably release today.

**Comment by kishikawakatsumi** [comment]
The iOS app has accepted the review. However, the macOS app was rejected for the following reasons: there is no difference in functionality between the iOS app and the macOS app, so as per usual Apple's review, this is not at all reasonable. However, it is necessary in order to distribute the app in the AppStore, so I will discuss it further.

> Guideline 2.1 - Information Needed
> 
> We have started our review, but we need additional information to continue. Specifically, it appears your app accesses or includes paid digital content or services, and we want to understand your business model before completing our review. 
> 
> Next Steps
> 
> Please review the following questions and provide as much detailed information about your business model as you can.
> 
> 1. Who are the users that will use the paid content, subscriptions, features, and services in the app?
> 2. Where can users purchase the content, subscriptions, features, and services that can be accessed in the app?
> 3. What specific types of previously purchased content, subscriptions, features, and services can a user access in the app?
> 4. What paid content, subscriptions, or features are unlocked within your app that do not use in-app purchase?
> 5. How do users obtain an account? Do users have to pay a fee to create an account?

**Comment by kishikawakatsumi** [comment]
macOS app has beed accepted 🎉
