### ISSUE TITLE
Incorrect page translation

### ISSUE THREAD

**Issue by vpravdivy** [kishikawakatsumi/WebTranslator#285]
**Steps to Reproduce:**
	1.	Open a webpage in a foreign language (e.g., German).
	2.	Log into the Deepl extension with a Pro subscription.
	3.	Select the target translation language (e.g., English).
	4.	Click the “Translate” button.

**Expected Result:**
The webpage should be fully translated into the selected language (English).

**Actual Result:**
	•	The extension displays an error message: “Sorry, we couldn’t translate your text. Please try again later.”
	•	The webpage remains in the original language (German), but after scrolling down, it suddenly gets translated into **Bulgarian**, which is the first language listed in the translation preferences.

**Additional Notes:**
	•	This problem has been observed on iOS for several months and now appears on macOS.
	•	The issue might be related to newer versions of iOS/macOS, as I’ve been using the iOS beta version since the summer, and I recently updated to the latest macOS.

https://github.com/user-attachments/assets/d918715d-36e0-4089-b556-59196e4ea335

**Comment by kishikawakatsumi** [comment]
Thanks reporting. The problem was reproduced on my end. I just haven't figured out how to fix it yet. Caused by iOS 18 and macOS Sequoia.
